version: "3"
services:
  # Test files
  test:
    volumes:
      - ./:/src/app
      - ./common/:/src/app/tests/common
    entrypoint: pytest --redis-host=redis
    command: .
    build:
      context: .
      dockerfile: tests/Dockerfile
      args:
        SPACY_LANG: "${SPACY_LANG}"
        SPACY_LOCAL: "${SPACY_LOCAL}"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      SPACY_LANG: "${SPACY_LANG}"
      SPACY_LOCAL: "${SPACY_LOCAL}"
    tty: true


  # Redis DB
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - "127.0.0.1:6379:6379"

